apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.app.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.app.registryCredentials }}
      imagePullSecrets:
        - name: {{ include "laravel-app.app.fullname" . }}-regcred
      {{- else }}
      {{- with .Values.app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      serviceAccountName: {{ include "laravel-app.app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            privileged: true
          command: ["/bin/sh", "-c"]
          args:
            - |
              mkdir -p /volume/app/storage
              cp -rn /srv/storage/* /volume/app/storage
              find /volume/app/storage -type d -exec chmod 777 {} +
              echo "Done"
          volumeMounts:
            - mountPath: /volume
              name: app-volume
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          {{- with .Values.app.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.app.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: {{ include "laravel-app.db.fullname" . }}
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_database | default "db_database" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_database
                  {{- end }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_username | default "db_username" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_username
                  {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_password | default "db_password" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_password
                  {{- end }}

          volumeMounts:
            {{- with .Values.app.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - mountPath: /srv/storage
              name: app-volume
              subPath: app/storage
            {{- end }}
      volumes:
        {{- with .Values.app.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: app-volume
          persistentVolumeClaim:
            claimName: {{ include "laravel-app.pvcName" . }}
        {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}