apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: {{ .Values.app.service.port }}
  selector:
    {{- include "laravel-app.app.selectorLabels" . | nindent 4 }}
