{{- if .Values.db.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "supabase.db.fullname" . }}-initdb
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
{{- range $path, $_ :=  .Files.Glob  "files/initdb/**.sql" }}
  {{ base $path }}: |-
    {{- $.Files.Get $path | nindent 4 }}
{{- end }}  
{{- end }}