{{- if not .Values.secrets.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
{{- if $value }}
{{- if or (eq (typeOf $value) "string") (eq (typeOf $value) "numeric") }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
