{{- if .Values.functions.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.functions.fullname" . }}-main
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  index.ts: |-
    {{- .Files.Get "files/functions/main/index.ts" | nindent 4}}
{{- end }}