{{- if .Values.db.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-app.db.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.db.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-app.db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.db.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel-app.db.selectorLabels" . | nindent 8 }}
        {{- with .Values.db.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.db.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel-app.db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.db.securityContext | nindent 12 }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: {{ .Values.db.service.port }}
              protocol: TCP
          {{- with .Values.db.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.db.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.db.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_rootpassword | default "db_rootpassword" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_rootpassword
                  {{- end }}
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_database | default "db_database" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_database
                  {{- end }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_username | default "db_username" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_username
                  {{- end }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.secrets.secretRef }}
                  name: {{ .Values.secrets.secretRef }}
                  key: {{ .Values.secrets.secretRefKey.db_password | default "db_password" }}
                  {{- else }}
                  name: {{ include "laravel-app.fullname" . }}
                  key: db_password
                  {{- end }}
          volumeMounts:
            {{- if .Values.db.initdbFile }}
            - mountPath: /docker-entrypoint-initdb.d
              name: db-initdb
            {{- end }}

            {{- with .Values.db.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - mountPath: /var/lib/mysql
              name: db-volume
              subPath: mysql-data
            {{- end }}
      volumes:
        {{- with .Values.db.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.db.initdbFile }}
        - name: db-initdb
          configMap:
            name: {{ include "laravel-app.db.fullname" . }}-initdb
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: db-volume
          persistentVolumeClaim:
            claimName: {{ include "laravel-app.pvcName" . }}
        {{- end }}
      {{- with .Values.db.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.db.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}